### ISSUE TITLE
User Story 2 - plurality

### ISSUE THREAD

**Issue by jbrucker** [WongNung/WongNung#1]
> I want to find somebody else that has the same film preferences as mine, so that I can follow other people’s recommendations on films.

* "I want to find other reviewers"  (not just one person)

* "the same film preferences" or "similar film preferences" or "nearly same film preferences"? 

* what's the *real* goal?  Is it to follow other people's recommendations or discover films that you might like?

**Comment by GToidZ** [comment]
We thank you for taking your time to point out the issues. We went ahead and fixed some wordings based on your suggestions. For the goal of User Story 2, it really is ambiguous; so, we re-wrote the purpose and it should be clearer.
