### ISSUE TITLE
[BUG]Genre Button from bookmark page does not respond

### ISSUE THREAD

**Issue by PloyyNK** [WongNung/WongNung#71]
### Description of Bug
As I got into my profile page and into the bookmark section, the genre button in each movie cannot click and respond as it is in the timeline page

### Expected Behavior/Fix (optional)
We should be redirected to the fandom page of that genre.
<img width="1552" alt="Screen Shot 2565-11-23 at 11 35 34" src="https://user-images.githubusercontent.com/89600864/203470340-ee69384a-e2b9-4411-b32d-554eeaebb504.png">

**Comment by GToidZ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [* Genres in film should be clickable.](https://trello.com/c/sJCGrR3R/69-genres-in-film-should-be-clickable)

**Comment by GToidZ** [comment]
It is confirmed that the current state, the genres in film details and bookmark cannot be clicked. Thanks for opening the issue.
