### ISSUE TITLE
[BUG] Multiple review when spamming post button

### ISSUE THREAD

**Issue by Tezigudo** [WongNung/WongNung#72]
### Description of Bug
![image](https://user-images.githubusercontent.com/80502090/203494105-9e678235-b3ad-4e3f-9a8c-6b81139946bf.png)

### Steps to Reproduce
I have publish a review and spamming Post button below 
![image](https://user-images.githubusercontent.com/80502090/203494519-3d27bcb6-daf5-4190-b70b-a35c40b30e18.png)

### Expected Behavior/Fix (optional)
it must get one post/review only after spamming post button

**Comment by GToidZ** [comment]
Did you test this in Safari?
