### ISSUE TITLE
[BUG] ScienceFiction tag

### ISSUE THREAD

**Issue by RyukungG** [WongNung/WongNung#76]
### Description of Bug
After click science fiction tag it didn't show any movie

### Steps to Reproduce
click science fiction tag

### Expected Behavior/Fix (optional)
After click movie tag it should show list of movie in that tag

**Comment by GToidZ** [comment]
This was already acknowledged and has been fixed with the commit in #73.

**Comment by GToidZ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [* Science Fiction is the only genre that doesn't really work as Fandom.](https://trello.com/c/zkisCx0U/67-science-fiction-is-the-only-genre-that-doesnt-really-work-as-fandom)
