### ISSUE TITLE
[BUG] Cannot edit an existing review. Creates a new review instead.

### ISSUE THREAD

**Issue by jbrucker** [WongNung/WongNung#79]
### Description of Bug
After writing and posting a descriptive review of The Martain, I click the Edit icon to revise the text.
The edit window is blank -- it creates a new review instead of letting me edit my previous review.

### Steps to Reproduce
1. select a movie
2. click the edit icon
3. enter a review and submit it
4. click the edit icon again (either in the same session or when revisiting the movie later)
5. you get an empty review edit window

### Expected Behavior/Fix (optional)
Specify how the application should behave.

**Comment by GToidZ** [comment]
Thank you for opening up the issue.

Quite possibly, we have overlook the manner of multiple reviews per film per person. The fix will be coming in `bug-fixes` branch ASAP.

**Comment by jbrucker** [comment]
Now when I click Edit, the review window displays (and let's me revise) my previous review.
I think this is the way users would expect it behave.
Thanks for fixing that.
