### ISSUE TITLE
Concise way to externalize database URL

### ISSUE THREAD

**Issue by jbrucker** [WongNung/WongNung#84]
https://github.com/WongNung/WongNung/blob/0cbb30d18ec2bac66c0d69e1308e2619cda5ce72/pdtx/settings.py#L122-L131

Looks like WongNung is the only team to externalize their database URL!
Good.

FYI, the package `dj-database-url` gives you a concise way of doing this, using just one variable.
The URL syntax is standard, too. 

```python
import dj_database_url as db_url

DATABASES = {
    'default': config('DATABASE_URL', cast=db_url.parse,
                       default="sqlite:///"+BASE_DIR+"db.sqlite3")
 }
```
and in `.env` or as an environment variable.
```
DATABASE_URL = postgres://username:password@localhost:5432/database_name
```
you can also omit parts (like the password) and specify them separately in `settings.py`, as you did.

**Comment by GToidZ** [comment]
Thank you for your suggestion, though we would not work on this enhancement anytime soon during this week. Maybe after we have more free time, we'll look into this option.
