### ISSUE TITLE
Remove django_recaptcha dependency from requirements.txt in wongnung-s branch

### ISSUE THREAD

**Issue by GToidZ** [WongNung/WongNung#91]
The modified lines of commit `5ac88c` has added a redundant django_recaptcha requirement. I suggest removing it so that it would not be installed without usage.

https://github.com/WongNung/WongNung/blob/5ac88c3e3668f54cf78e5ecec34327791c508a95/requirements/common.txt#L13-L14

**Comment by Savetang19** [comment]
I have resolved this issue with this [PR](https://github.com/WongNung/WongNung/pull/92)
